### ISSUE TITLE
Toolbox: LESS Hat Keyframe converter

### ISSUE THREAD

**Issue by bennycode** [bennyn/wlc-webapp#131]
Converts webkit-keyframe animations into LESS Hat animations.
## Example

**From**

``` css
@-webkit-keyframes animationName {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}
```

**To**

``` css
.lh-keyframes(~'animationName, 0%{ opacity: 0; } 100%{ opacity: 1; }');
```

**Another approach**

`.lh-keyframes` kann nicht genutzt werden, wenn innerhalb der Animation schon LESS Mixins benutzt werden (wie etwa `.lh-scale`). Daher muss Folgendes bei der Konvertierung erzeugt werden:

``` css
@keyframes animationName { .animationName; }
@-o-keyframes animationName { .animationName; }
@-ms-keyframes animationName { .animationName; }
@-moz-keyframes animationName { .animationName; }
@-webkit-keyframes animationName { .animationName; }

.animationName() {
  0% {
    opacity: 0;
    .lh-scale(1);
  }

  100% {
    opacity: 1;
    .lh-scale(1.5);
  }
}
```

Note:

LESS Hat animations must be written in a single line. We should also give support to switch on and off the LESS Hat prefix `.lh-`.
